framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    handle_all_throwables: false
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        storage_factory_id: session.storage.factory.native
        cookie_samesite: lax
        cookie_secure: auto
        handler_id: session.handler.native_file
    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
      utf8: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
